using System;
using System.Collections.Generic;
using System.Text;

namespace FFRKApi.Model.EnlirTransform.IdLists
{
    public class OrbTypeList : ITypeList
    {
        private IList<KeyValuePair<int, string>> _typeList = new List<KeyValuePair<int, string>>()
                                                             {
                                                                 new KeyValuePair<int, string>(0, "Unknown"),
                                                                 new KeyValuePair<int, string>(1, String.Empty),
                                                                 new KeyValuePair<int, string>(2, "Ability Record"),
                                                                 new KeyValuePair<int, string>(3, "Minor Black"),
                                                                 new KeyValuePair<int, string>(4, "Lesser Black"),
                                                                 new KeyValuePair<int, string>(5, "Black"),
                                                                 new KeyValuePair<int, string>(6, "Greater Black"),
                                                                 new KeyValuePair<int, string>(7, "Major Black"),
                                                                 new KeyValuePair<int, string>(8, "Black Crystal"),
                                                                 new KeyValuePair<int, string>(9, "Minor Dark"),
                                                                 new KeyValuePair<int, string>(10, "Lesser Dark"),
                                                                 new KeyValuePair<int, string>(11, "Dark"),
                                                                 new KeyValuePair<int, string>(12, "Greater Dark"),
                                                                 new KeyValuePair<int, string>(13, "Major Dark"),
                                                                 new KeyValuePair<int, string>(14, "Dark Crystal"),
                                                                 new KeyValuePair<int, string>(15, "Minor Earth"),
                                                                 new KeyValuePair<int, string>(16, "Lesser Earth"),
                                                                 new KeyValuePair<int, string>(17, "Earth"),
                                                                 new KeyValuePair<int, string>(18, "Greater Earth"),
                                                                 new KeyValuePair<int, string>(19, "Major Earth"),
                                                                 new KeyValuePair<int, string>(20, "Earth Crystal"),
                                                                 new KeyValuePair<int, string>(21, "Minor Fire"),
                                                                 new KeyValuePair<int, string>(22, "Lesser Fire"),
                                                                 new KeyValuePair<int, string>(23, "Fire"),
                                                                 new KeyValuePair<int, string>(24, "Greater Fire"),
                                                                 new KeyValuePair<int, string>(25, "Major Fire"),
                                                                 new KeyValuePair<int, string>(26, "Fire Crystal"),
                                                                 new KeyValuePair<int, string>(27, "Minor Holy"),
                                                                 new KeyValuePair<int, string>(28, "Lesser Holy"),
                                                                 new KeyValuePair<int, string>(29, "Holy"),
                                                                 new KeyValuePair<int, string>(30, "Greater Holy"),
                                                                 new KeyValuePair<int, string>(31, "Major Holy"),
                                                                 new KeyValuePair<int, string>(32, "Holy Crystal"),
                                                                 new KeyValuePair<int, string>(33, "Minor Ice"),
                                                                 new KeyValuePair<int, string>(34, "Lesser Ice"),
                                                                 new KeyValuePair<int, string>(35, "Ice"),
                                                                 new KeyValuePair<int, string>(36, "Greater Ice"),
                                                                 new KeyValuePair<int, string>(37, "Major Ice"),
                                                                 new KeyValuePair<int, string>(38, "Ice Crystal"),
                                                                 new KeyValuePair<int, string>(39, "Minor Lightning"),
                                                                 new KeyValuePair<int, string>(40, "Lesser Lightning"),
                                                                 new KeyValuePair<int, string>(41, "Lightning"),
                                                                 new KeyValuePair<int, string>(42, "Greater Lightning"),
                                                                 new KeyValuePair<int, string>(43, "Major Lightning"),
                                                                 new KeyValuePair<int, string>(44, "Lightning Crystal"),
                                                                 new KeyValuePair<int, string>(45, "Minor Non-Elemental"),
                                                                 new KeyValuePair<int, string>(46, "Lesser Non-Elemental"),
                                                                 new KeyValuePair<int, string>(47, "Non-Elemental"),
                                                                 new KeyValuePair<int, string>(48, "Greater Non-Elemental"),
                                                                 new KeyValuePair<int, string>(49, "Major Non-Elemental"),
                                                                 new KeyValuePair<int, string>(50, "Non-Elemental Crystal"),
                                                                 new KeyValuePair<int, string>(51, "Minor Power"),
                                                                 new KeyValuePair<int, string>(52, "Lesser Power"),
                                                                 new KeyValuePair<int, string>(53, "Power"),
                                                                 new KeyValuePair<int, string>(54, "Greater Power"),
                                                                 new KeyValuePair<int, string>(55, "Major Power"),
                                                                 new KeyValuePair<int, string>(56, "Power Crystal"),
                                                                 new KeyValuePair<int, string>(57, "Minor Summon"),
                                                                 new KeyValuePair<int, string>(58, "Lesser Summon"),
                                                                 new KeyValuePair<int, string>(59, "Summon"),
                                                                 new KeyValuePair<int, string>(60, "Greater Summon"),
                                                                 new KeyValuePair<int, string>(61, "Major Summon"),
                                                                 new KeyValuePair<int, string>(62, "Summoning Crystal"),
                                                                 new KeyValuePair<int, string>(63, "Minor White"),
                                                                 new KeyValuePair<int, string>(64, "Lesser White"),
                                                                 new KeyValuePair<int, string>(65, "White"),
                                                                 new KeyValuePair<int, string>(66, "Greater White"),
                                                                 new KeyValuePair<int, string>(67, "Major White"),
                                                                 new KeyValuePair<int, string>(68, "White Crystal"),
                                                                 new KeyValuePair<int, string>(69, "Minor Wind"),
                                                                 new KeyValuePair<int, string>(70, "Lesser Wind"),
                                                                 new KeyValuePair<int, string>(71, "Wind"),
                                                                 new KeyValuePair<int, string>(72, "Greater Wind"),
                                                                 new KeyValuePair<int, string>(73, "Major Wind"),
                                                                 new KeyValuePair<int, string>(74, "Wind Crystal")
                                                             };

        public IList<KeyValuePair<int, string>> TypeList => _typeList;
    }
}
