using System;
using System.Collections.Generic;
using System.Text;

namespace FFRKApi.Model.EnlirTransform.IdLists
{
    public class OrbTypeList : ITypeList
    {
        private IList<KeyValuePair<int, string>> _typeList = new List<KeyValuePair<int, string>>()
                                                             {
                                                                 new KeyValuePair<int, string>(0, "Unknown"),
                                                                 new KeyValuePair<int, string>(1, "Minor Black"),
                                                                 new KeyValuePair<int, string>(2, "Lesser Black"),
                                                                 new KeyValuePair<int, string>(3, "Black"),
                                                                 new KeyValuePair<int, string>(4, "Greater Black"),
                                                                 new KeyValuePair<int, string>(5, "Major Black"),
                                                                 new KeyValuePair<int, string>(6, "Black Crystal"),
                                                                 new KeyValuePair<int, string>(7, "Minor Dark"),
                                                                 new KeyValuePair<int, string>(8, "Lesser Dark"),
                                                                 new KeyValuePair<int, string>(9, "Dark"),
                                                                 new KeyValuePair<int, string>(10, "Greater Dark"),
                                                                 new KeyValuePair<int, string>(11, "Major Dark"),
                                                                 new KeyValuePair<int, string>(12, "Dark Crystal"),
                                                                 new KeyValuePair<int, string>(13, "Minor Earth"),
                                                                 new KeyValuePair<int, string>(14, "Lesser Earth"),
                                                                 new KeyValuePair<int, string>(15, "Earth"),
                                                                 new KeyValuePair<int, string>(16, "Greater Earth"),
                                                                 new KeyValuePair<int, string>(17, "Major Earth"),
                                                                 new KeyValuePair<int, string>(18, "Earth Crystal"),
                                                                 new KeyValuePair<int, string>(19, "Minor Fire"),
                                                                 new KeyValuePair<int, string>(20, "Lesser Fire"),
                                                                 new KeyValuePair<int, string>(21, "Fire"),
                                                                 new KeyValuePair<int, string>(22, "Greater Fire"),
                                                                 new KeyValuePair<int, string>(23, "Major Fire"),
                                                                 new KeyValuePair<int, string>(24, "Fire Crystal"),
                                                                 new KeyValuePair<int, string>(25, "Minor Holy"),
                                                                 new KeyValuePair<int, string>(26, "Lesser Holy"),
                                                                 new KeyValuePair<int, string>(27, "Holy"),
                                                                 new KeyValuePair<int, string>(28, "Greater Holy"),
                                                                 new KeyValuePair<int, string>(29, "Major Holy"),
                                                                 new KeyValuePair<int, string>(30, "Holy Crystal"),
                                                                 new KeyValuePair<int, string>(31, "Minor Ice"),
                                                                 new KeyValuePair<int, string>(32, "Lesser Ice"),
                                                                 new KeyValuePair<int, string>(33, "Ice"),
                                                                 new KeyValuePair<int, string>(34, "Greater Ice"),
                                                                 new KeyValuePair<int, string>(35, "Major Ice"),
                                                                 new KeyValuePair<int, string>(36, "Ice Crystal"),
                                                                 new KeyValuePair<int, string>(37, "Minor Lightning"),
                                                                 new KeyValuePair<int, string>(38, "Lesser Lightning"),
                                                                 new KeyValuePair<int, string>(39, "Lightning"),
                                                                 new KeyValuePair<int, string>(40, "Greater Lightning"),
                                                                 new KeyValuePair<int, string>(41, "Major Lightning"),
                                                                 new KeyValuePair<int, string>(42, "Lightning Crystal"),
                                                                 new KeyValuePair<int, string>(43, "Minor Non-Elemental"),
                                                                 new KeyValuePair<int, string>(44, "Lesser Non-Elemental"),
                                                                 new KeyValuePair<int, string>(45, "Non-Elemental"),
                                                                 new KeyValuePair<int, string>(46, "Greater Non-Elemental"),
                                                                 new KeyValuePair<int, string>(47, "Major Non-Elemental"),
                                                                 new KeyValuePair<int, string>(48, "Non-Elemental Crystal"),
                                                                 new KeyValuePair<int, string>(49, "Minor Power"),
                                                                 new KeyValuePair<int, string>(50, "Lesser Power"),
                                                                 new KeyValuePair<int, string>(51, "Power"),
                                                                 new KeyValuePair<int, string>(52, "Greater Power"),
                                                                 new KeyValuePair<int, string>(53, "Major Power"),
                                                                 new KeyValuePair<int, string>(54, "Power Crystal"),
                                                                 new KeyValuePair<int, string>(55, "Minor Summon"),
                                                                 new KeyValuePair<int, string>(56, "Lesser Summon"),
                                                                 new KeyValuePair<int, string>(57, "Summon"),
                                                                 new KeyValuePair<int, string>(58, "Greater Summon"),
                                                                 new KeyValuePair<int, string>(59, "Major Summon"),
                                                                 new KeyValuePair<int, string>(60, "Summon Crystal"),
                                                                 new KeyValuePair<int, string>(61, "Minor White"),
                                                                 new KeyValuePair<int, string>(62, "Lesser White"),
                                                                 new KeyValuePair<int, string>(63, "White"),
                                                                 new KeyValuePair<int, string>(64, "Greater White"),
                                                                 new KeyValuePair<int, string>(65, "Major White"),
                                                                 new KeyValuePair<int, string>(66, "White Crystal"),
                                                                 new KeyValuePair<int, string>(67, "Minor Wind"),
                                                                 new KeyValuePair<int, string>(68, "Lesser Wind"),
                                                                 new KeyValuePair<int, string>(69, "Wind"),
                                                                 new KeyValuePair<int, string>(70, "Greater Wind"),
                                                                 new KeyValuePair<int, string>(71, "Major Wind"),
                                                                 new KeyValuePair<int, string>(72, "Wind Crystal"),
                                                                 new KeyValuePair<int, string>(73, "Affliction Break Record"),
                                                                 new KeyValuePair<int, string>(74, "Crushdown Record"),
                                                                 new KeyValuePair<int, string>(75, "Curada Record"),
                                                                 new KeyValuePair<int, string>(76, "Dervish Record"),
                                                                 new KeyValuePair<int, string>(77, "Meltdown Record"),
                                                                 new KeyValuePair<int, string>(78, "Neo Bahamut Record"),
                                                                 new KeyValuePair<int, string>(79, "Northern Cross Record"),
                                                                 new KeyValuePair<int, string>(80, "Omega Drive Record"),
                                                                 new KeyValuePair<int, string>(81, "Quadruple Foul Record"),
                                                                 new KeyValuePair<int, string>(82, "Reraise Record"),
                                                                 new KeyValuePair<int, string>(83, "Ultima Record"),
                                                                 new KeyValuePair<int, string>(84, "Valigarmanda Record")
                                                             };

        public IList<KeyValuePair<int, string>> TypeList => _typeList;
    }
}
